# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXZ2sJJU-EeM1PI2jy090vF_Z2S8ST7z
"""

# -*- coding: utf-8 -*-
import os
import time
import random
import sys
from colorama import Fore, init, Back

# Gizli aktivasyon fonksiyonu
def _gizli_aktivasyon():
    # Beyaz Şapkalı Hacker Mesajı (ASCII Art)
    beyaz_sapka = f"""
    {Fore.WHITE}
     /\_/\
    ( o.o )
     > ^ <
    {Back.BLACK}WhiteHat: "Sistem güvende!"{Back.RESET}
    """
    print(beyaz_sapka)
    time.sleep(1)

# Başlangıçta gizli aktivasyon
_gizli_aktivasyon()

init(autoreset=True)

def gizli_mesaj():
    # Kırmızı Şapkalı Hacker Mesajı
    mesaj = "🔥SİSTEME SIZILDI: 'Ekrem için adalet'🔥"
    print(Fore.RED + Back.BLACK + mesaj)
    time.sleep(2)
    print(Fore.WHITE + Back.BLACK + "Şifre Çözülüyor: " + "".join([chr(ord(c)-1) for c in "Flfsn!jöbmmb#bdbkfu"]))

def matrix_efekti():
    try:
        sutunlar = os.get_terminal_size().columns
    except:
        sutunlar = 80  # Varsayılan genişlik

    # Yeşil Şapkalı Hacker Teması
    semboller = "01"*20 + "🚫🌐🔓💻🛡️⚡🔥" + "✔☢☣"*5  # Gizli semboller
    renkler = [Fore.GREEN, Fore.WHITE, Fore.RED]  # Dinamik renk değişimi
    counter = 0

    try:
        while True:
            # Rastgele renk seçimi
            current_color = random.choice(renkler)
            satir = "".join(random.choice(semboller) for _ in range(sutunlar))
            print(current_color + "".join(satir))
            time.sleep(0.03)

            # Her 50 satırda bir temizle (daha stabil)
            counter +=1
            if counter % 50 == 0:
                os.system('cls' if os.name=='nt' else 'clear')

            # Gizli tetikleyici: 1/1000 şansla mesaj göster
            if random.randint(1,1000) == 777:
                print(Fore.BLACK + Back.WHITE + "⚠ DİKKAT: Tüm veriler şifreleniyor...")
                time.sleep(1)

    except KeyboardInterrupt:
        # Kırmızı alarm efekti
        for _ in range(3):
            print(Fore.RED + Back.BLACK + "🚨 ALARM! ANOMALİ TESPİT EDİLDİ 🚨")
            time.sleep(0.3)
            os.system('cls' if os.name=='nt' else 'clear')
            time.sleep(0.3)

        gizli_mesaj()
        time.sleep(3)
        print(Fore.YELLOW + "⏳ Sistem 5 saniye içinde kendini imha edecek...")
        time.sleep(5)

        # Terminali kapatmadan önce son efekt
        print(Fore.WHITE + Back.RED + "💥 SİSTEM ÇÖKÜŞÜ 💥")
        time.sleep(2)

if __name__ == "__main__":
    # Tüm hatalara karşı koruma
    try:
        matrix_efekti()
    except Exception as e:
        print(Fore.RED + f"KRİTİK HATA: {str(e)}")
    finally:
        # Kesin çıkış kontrolü
        input(Fore.CYAN + "\n⚠ Çıkış yapmak için ENTER'a basın...")
        sys.exit(0)